import localFont from "next/font/local";
import "./globals.css";
import { authOptions } from "@/utils/authOptions";
import SessionWrapper from "@/components/SessionWrapper";
import DataState from "@/context/Data/DataState";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const session = await getServerSession(authOptions);
  return (
    <SessionWrapper>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
            <DataState>
            {children}
          </DataState>
          </body>
        </html>
    </SessionWrapper>
  );
}
