export const GET_PROFILE = "GET_PROFILE" 
export const PROFILE_DATA = "PROFILE_DATA" 
export const GET_ORG_PROFILE = "GET_ORG_PROFILE" 
export const ORG_PROFILE_DATA = "ORG_PROFILE_DATA" 
export const GET_COUNTRIES = "GET_COUNTRIES" 
export const COUNTRIES_LIST = "COUNTRIES_LIST" 
export const SET_EMAIL_PREFERNCES = "SET_EMAIL_PREFERNCES" 


export const EDIT_PROFILE = "EDIT_PROFILE"
export const PROFILE_SUCCESS = "PROFILE_SUCCESS"
export const PROFILE_ERROR = "PROFILE_ERROR"
export const RESET_PROFILE_FLAG = "RESET_PROFILE_FLAG";